#ifndef KEYS_H_INCLUDED
#define KEYS_H_INCLUDED

namespace Keys
{
    typedef enum Keys_t
    {
        LBUTTON = 0x01,
        RBUTTON,
        CANCEL,
        MBUTTON,
        XBUTTON1,
        XBUTTON2,
        UNDEFINED,
        BACKSPACE,
        TAB,
        RESERVED,
        CLEAR,
        RETURN = 0x0D,
        SHIFT = 0x10,
        CONTROL,
        MENU,
        PAUSE,
        CAPITAL,
        KANA,
        HANGUEL,
        HANGUL,
        UNDEFINED2,
        JUNJA,
        FINAL,
        HANJA,
        KANJI,
        UNDEFINED3,
        ESCAPE,
        CONVERT,
        NONCONVERT,
        ACCEPT,
        MODECHANGE,
        SPACE = 0x20,
        PRIOR,
        NEXT,
        END,
        HOME,
        LEFT,
        UP,
        RIGHT,
        DOWN,
        SELECT,
        PRINT,
        EXECUTE,
        SNAPSHOT,
        INSERT,
        DELETE_KEY,
        HELP,
        ZERO,
        ONE,
        TWO,
        THREE,
        FOUR,
        FIVE,
        SIX,
        SEVEN,
        EIGHT,
        NINE,
        A = 0x41,
        B,
        C,
        D,
        E,
        F,
        G,
        H,
        I,
        J,
        K,
        L,
        M,
        N,
        O,
        P,
        Q,
        R,
        S,
        T,
        U,
        V,
        W,
        X,
        Y,
        Z,
        LWIN,

        RWIN,
        APPS,
        RESERVED2,
        SLEEP,

        NUMPAD0,
        NUMPAD1,

        NUMPAD2,
        NUMPAD3,

        NUMPAD4,
        NUMPAD5,
        NUMPAD6,

        NUMPAD7,
        NUMPAD8,
        NUMPAD9,
        MULTIPLY,

        ADD,
        SEPARATOR,
        SUBTRACT,

        DECIMAL_KEY,
        DIVIDE,
        F1,
        F2,
        F3,
        F4,
        F5,
        F6,
        F7,
        F8,

        F9,
        F10,
        F11,
        F12,
        F13,
        F14,
        F15,

        F16,
        F17,
        F18,
        F19,
        F20,
        F21,
        F22,
        F23,
        F24,
        NUMLOCK = 0x90,
        SCROLL,
        LSHIFT = 0xA0,
        RSHIFT,
        LCONTROL,
        RCONTROL,
        LMENU,
        RMENU,
        BROWSER_BACK,
        BROWSER_FORWARD,
        BROWSER_REFRESH,
        BROWSER_STOP,
        BROWSER_SEARCH,
        BROWSER_FAVORITES,
        BROWSER_HOME,
        VOLUME_MUTE,
        VOLUME_DOWN,
        VOLUME_UP,
        MEDIA_NEXT_TRACK,
        MEDIA_PREV_TRACK,
        MEDIA_STOP,
        MEDIA_PLAY_PAUSE,
        LAUNCH_APP1,
        LAUNCH_APP2,
        OEM_1 = 0xBA,
        OEM_PLUS,
        OEM_COMMA = 0xBC,
        OEM_MINUS,
        OEM_PERIOD,
        OEM_2 = 0xBF,
        OEM_3,
        OEM_4 = 0xDB,
        OEM_5,
        OEM_6,
        OEM_7,
        OEM_8
    } Key;
}

#endif // KEYS_H_INCLUDED
